from __future__ import annotations

import ast
import csv
import json
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Thai_Lotto_updated.csv"
OUTPUT = ROOT / "supabase" / "seed.sql"


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def parse_date(raw: str) -> str:
    return datetime.strptime(raw, "%d/%m/%Y").strftime("%Y-%m-%d")


def parse_digits(raw: str) -> str:
    values = ast.literal_eval(raw)
    return json.dumps(values, ensure_ascii=False)


def build_insert(row: dict[str, str]) -> str:
    draw_date = parse_date(row["date"])
    first_prize = row["prize_1st"]
    front_3_digits = parse_digits(row["prize_pre_3digit"])
    back_3_digits = parse_digits(row["prize_sub_3digits"])
    last_2_digits = row["prize_2digits"]

    return (
        "insert into public.lotto_results "
        "(draw_date, first_prize, front_3_digits, back_3_digits, last_2_digits, source_file)\n"
        f"values ({sql_quote(draw_date)}, {sql_quote(first_prize)}, "
        f"{sql_quote(front_3_digits)}::jsonb, {sql_quote(back_3_digits)}::jsonb, "
        f"{sql_quote(last_2_digits)}, 'Thai_Lotto_updated.csv')\n"
        "on conflict (draw_date) do update set\n"
        "  first_prize = excluded.first_prize,\n"
        "  front_3_digits = excluded.front_3_digits,\n"
        "  back_3_digits = excluded.back_3_digits,\n"
        "  last_2_digits = excluded.last_2_digits,\n"
        "  source_file = excluded.source_file,\n"
        "  updated_at = now();\n"
    )


def main() -> None:
    with SOURCE.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = [row for row in csv.DictReader(handle) if row.get("date")]

    header = [
        "-- Generated by scripts/export_seed_sql.py",
        "-- Source: Thai_Lotto_updated.csv",
        "",
        "begin;",
        "",
    ]
    body = [build_insert(row) for row in rows]
    footer = ["", "commit;", ""]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(header + body + footer), encoding="utf-8")


if __name__ == "__main__":
    main()
